require("runtime-jcmpTestBase")
local player = Server:GetPlayers()()
assert(Events.Handlers.ClientModuleLoad {player = player} == true)
assert(Events.Handlers.PlayerChat {player = player, text = "/up"} == false)
assert(player.position.y == 100)
assert(Events.Handlers.PlayerChat {player = player, text = "/down"} == false)
assert(player.position.y == 0)
assert(Events.Handlers.PlayerChat {player = player, text = "/invalid"} == true)
assert(Events.Handlers.ModuleUnload {} == true)
